### PR TITLE
Respect fail closed on deadlines

### LINKED ISSUE #1283: deadline exceeded in monitor mode still ends up denying execution
When deadlines are exceeded here:

https://github.com/google/santa/blob/e8db89c57c41dde73fa447bca206faf9075eb484/Source/santad/EventProviders/SNTEndpointSecurityClient.mm#L296-L299

The process is still denied execution even if Santa is in monitor mode.

Also: these denials are not logged in the normal ALLOW/DENY logging (that end up in `/var/db/santa/santa.log*` files.

### PR DESCRIPTION
**Pull request by mlw**
Santa attempts to respond to events before system deadlines in case event processing took too long for some reason. This previously only resulted in events being denied.

This PR changes two things related to the default respons Santa will make before deadlines expire:

1. When in `Lockdown` mode, `FailClosed` configuration will now be respected
2. When in `Monitor` mode, Santa will ALLOW the events

Fixes #1283

### CODE REVIEW

**Review by kallsyms — APPROVED** [review]

File: Source/common/SNTConfigurator.m [hunk 1]
```diff
@@ -604,8 +604,11 @@ - (void)setSyncServerClientMode:(SNTClientMode)newMode {
 
 - (BOOL)failClosed {
   NSNumber *n = self.configState[kFailClosedKey];
-  if (n) return [n boolValue];
-  return NO;
+  if ([n boolValue] && self.clientMode == SNTClientModeLockdown) {
+    return YES;
+  } else {
+    return NO;
+  }
```
Comment (russellhancox) [inline Source/common/SNTConfigurator.m:611]: `return [n boolValue] && self.clientMode == SNTClientModeLockdown`

**Review by russellhancox — APPROVED** [review]

**Review by russellhancox — APPROVED** [review]
