### PR TITLE
santad: Fix decision fetching for certs by hash

### LINKED ISSUE #463: Incorrect result when checking certificate rule via "santactl rule --check ..."
I've blacklisted the Mozilla certificate using:

`santactl rule --blacklist --certificate --sha256 96f18e09d65445985c7df5df74ef152a0bc42e8934175a626180d9700c343e7b`

The blacklisting is successful, Firefox is blocked from loading.

I then do a check on the rule using:

`santactl rule --check --certificate --sha256 96f18e09d65445985c7df5df74ef152a0bc42e8934175a626180d9700c343e7b`

The output of the check is `Whitelisted (Unknown)`.

However, `santctl fileinfo /Applications/Firefox.app` for Rule produces `Blacklisted (Certificate)`.

```
santactl version
santa-driver    | un-needed (SystemExtension being used)
santad          | 1.13
santactl        | 1.13
SantaGUI        | 1.13

### PR DESCRIPTION
**Pull request by russellhancox**
Fixes #463

### CODE REVIEW

File: Source/santad/SNTPolicyProcessor.m [hunk 1]
```diff
@@ -48,19 +49,23 @@ - (nonnull SNTCachedDecision *)decisionForFileInfo:(nonnull SNTFileInfo *)fileIn
...
+    cd.certSHA256 = certificateSHA256;
+  } else {
+    // Grab the code signature, if there's an error don't try to capture
+    // any of the signature details.
+    MOLCodesignChecker *csInfo = [fileInfo codesignCheckerWithError:&csInfoError];
+    if (csInfoError) {
+      csInfo = nil;
+      cd.decisionExtra =
+          [NSString stringWithFormat:@"Signature ignored due to error: %ld", (long)csInfoError.code];
+    }
```
Comment (tburgin) [inline Source/santad/SNTPolicyProcessor.m:63]: nit: save some nil message sends.
```
if (csInfoError) {
...
} else {
  cd.certSHA256 = csInfo.leafCertificate.SHA256;
  cd.certCommonName = csInfo.leafCertificate.commonName;
  cd.certChain = csInfo.certificates;
}
```

Comment (russellhancox) [reply Source/santad/SNTPolicyProcessor.m:67]: Done
