### PR TITLE
Fix SNTFileInfoTest for macOS 13

### LINKED ISSUE #886: Make sure unit-tests can account for new paths in macOS 13
Many of our unit tests e.g. those in `SNTFileInfoTest`, reference absolute paths like `/Applicaitions/Safari.app` which on macOS 13 are symlinks to `/System/Cryptexes/App/System/Applications/Safari.app` as such tests fail.

### PR DESCRIPTION
**Pull request by pmarkowsky**
This PR updates `SNTFileInfo` unit tests to account for Safari coming from a [cryptex](https://eclecticlight.co/2022/11/16/cryptex-how-a-custom-iphone-is-changing-macos-updates/) on macOS 13. Also skips the KEXT test on macOS 13 due to KEXTs moving into the kernel cache.

Fixes #886

### CODE REVIEW

File: Source/common/SNTFileInfoTest.m [hunk 1]
```diff
@@ -34,7 +34,12 @@ - (NSString *)bundleExample {
 - (void)testPathStandardizing {
   SNTFileInfo *sut = [[SNTFileInfo alloc] initWithPath:@"/Applications/Safari.app"];
   XCTAssertNotNil(sut);
-  XCTAssertEqualObjects(sut.path, @"/Applications/Safari.app/Contents/MacOS/Safari");
+  if (@available(macOS 13.0, *)) {
+    XCTAssertEqualObjects(sut.path, @"/System/Volumes/Preboot/Cryptexes/App/System/Applications/"
+                                    @"Safari.app/Contents/MacOS/Safari");
+  } else {
+    XCTAssertEqualObjects(sut.path, @"/System/Safari.app/Contents/MacOS/Safari");
```
Comment (russellhancox) [inline Source/common/SNTFileInfoTest.m:41]: s/System/Applications

**Review by russellhancox — CHANGES_REQUESTED** [review]

**Review by russellhancox — APPROVED** [review]

**Review by mlw — APPROVED** [review]
